#!/bin/sh

#clean up 
rm segment*ts
rm playlist.m3u8*

# capture local camera - not optimized
gst-launch-1.0 v4l2src device="/dev/video0" ! videoconvert ! clockoverlay ! \
x264enc tune=zerolatency ! mpegtsmux ! \
hlssink playlist-root=http://10.0.0.27:8080 location=/home/chris/projects/hls/segment_%05d.ts target-duration=5 max-files=5
